#file: noinspection UndefinedParamsPresent,UndefinedAction
on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set Up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.5.x
          enable-cache: true

      - name: Install Dependencies
        run: uv sync

      - name: Restore Bun Cache
        uses: actions/cache/restore@v4
        with:
          path: .web
          key: ${{ runner.os }}-bun-${{ hashFiles('.web/bun.lockb') }}

      - name: Export Frontend
        run: uv run reflex export --frontend-only --loglevel debug
        env:
          API_URL: https://reflex.celsiusnarhwal.dev/api

      - name: Save Bun Cache
        uses: actions/cache/save@v4
        with:
          path: .web
          key: ${{ runner.os }}-bun-${{ hashFiles('.web/bun.lockb') }}

      - name: Deploy to Railway
        run: npx @railway/cli up -s app --ci
