on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      REFLEX_LOG_LEVEL: debug
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set Up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.5.x
          enable-cache: true

      - name: Install Dependencies
        run: uv sync

      - name: Set Up Bun Cache
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('.web/bun.lockb') }}

      - name: Export Frontend
        run: | 
          uv run reflex export --frontend-only --no-zip --loglevel debug
          mkdir srv; mv .web/_static srv/
        env:
          API_URL: https://reflex.celsiusnarhwal.dev/api


      - name: Deploy to Railway
        run: npx @railway/cli up -s app --ci
