#file: noinspection UndefinedParamsPresent,UndefinedAction
on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set Up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.5.x
          enable-cache: true

      - name: Set Up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: uv sync

      - name: Set Bun Path
        shell: uv run --with github-action-utils python {0}
        run: |
          import github_action_utils as gha
          from reflex.config import get_config

          gha.add_system_path(get_config().bun_path.parent)

      - name: Restore Bun Cache
        uses: actions/cache/restore@v4
        with:
          path: .web
          key: ${{ runner.os }}-bun-${{ hashFiles('.web/bun.lockb') }}

      - name: Export Frontend
        run: bun install --cwd .web --frozen-lockfile; uv run reflex export --frontend-only --loglevel debug
        env:
          API_URL: https://reflex.celsiusnarhwal.dev/api
          REFLEX_USE_SYSTEM_BUN: true

      - name: Save Bun Cache
        uses: actions/cache/save@v4
        with:
          path: .web
          key: ${{ runner.os }}-bun-${{ hashFiles('.web/bun.lockb') }}

      - name: Deploy to Railway
        run: npx @railway/cli up -s app --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
