#file: noinspection UndefinedParamsPresent,UndefinedAction
on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set Up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.5.x
          enable-cache: true

      - name: Install Dependencies
        run: uv sync
        working-directory: repo

      - name: Export Frontend
        uses: celsiusnarhwal/reflex-export@main
        with:
          args: --frontend-only --loglevel debug
        env:
          FONTAWESOME_PACKAGE_TOKEN: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}
          API_URL: https://reflex.celsiusnarhwal.dev/api

      - name: Deploy to Railway
        run: npx @railway/cli up -s app --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
